'use client'

import { useState } from "react";
import {Flashcard} from "@/types/flashcard";
import NewFlashcard from "@/app/create/NewFlashcard";
import AddIcon from '@mui/icons-material/Add';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import {Button} from "@/components/ui/button"
import {Textarea} from "@/components/ui/textarea"
import {createClient} from "@/utils/supabase/client"
import {useRouter} from "next/navigation";
import "@/app/globals.css"
import {TypographyP} from "@/components/ui/typography";

export default function CreateForm() {
    const [cards, setCards] = useState<Flashcard[]>([{id: 0, front: "", back: ""}]);
    const [nextID, setNextID] = useState(1);
    const [index, setIndex] = useState(0)
    const [stackName, setStackName] = useState("")
    const [autoTranslate, setAutoTranslate] = useState(true)
    const [cardsFilled, setCardsFilled] = useState(false)
    const supabase = createClient()
    const router = useRouter()


    const addCard = () => {
        setCards(prev => [
            ...prev,
            { id: nextID, front: "", back: "" }
        ]);
        setNextID(nextID => nextID + 1)
        setIndex(index => index + 1)
        setCardsFilled(false)
    };

    const updateCard = (id: number, changes: Partial<Flashcard>) => {
        setCards(prev =>
            prev.map(card =>
                card.id == id ? { ...card, ...changes } : card
            )
        );
    };

    const deleteCard = (id: number) => {
        setCards(prev => prev.filter(card => card.id !== id));
    };

    const saveStack = async () => {
        const {
            data: {user}
        } = await supabase.auth.getUser()

        //save the flashcard stack object first
        const {data, error} = await supabase
            .from('flashcard_sets')
            .insert([
                {
                    user_id: user!.id,
                    //stack_id automatically generated by supabase
                    stack_name: stackName
                }
            ])
            .select('stack_id')

        //save each flashcard in the stack
        for (const card of cards) {
            await supabase
                .from('flashcards')
                .insert([
                    {
                        stack_id: data![0].stack_id,
                        front: card.front,
                        back: card.back
                    }
                ])
        }

        //redirect user to home page
        router.push("/")

    }

    return (
        <div className="grid grid-cols-4 grid-rows-4 w-screen h-screen">
            <Textarea
                value={stackName}
                onChange={(e) => setStackName(e.target.value)}
                placeholder="Stack name"
                rows={2}
                className={"col-span-2 col-start-2 row-span-1 row-start-1 min-h-[auto] self-center text-center text-3xl md:text-3xl resize-none"}
            />
            <div
                className={"col-span-2 col-start-2 row-span-2 row-start-2"}>
                <TypographyP className="text-center mb-1">Card {index + 1} of {cards.length}</TypographyP>
                <NewFlashcard
                    key={cards[index].id}
                    card={cards[index]}
                    onUpdate={updateCard}
                    onDelete={deleteCard}
                    autoTranslate={autoTranslate}
                />
            </div>
            {index !== 0 ?
                <Button
                    onClick={() => setIndex(index => index - 1)}
                    className={"row-start-2 row-span-2 col-start-1 col-span-1 w-fit h-fit self-center justify-self-center"}
                >
                    <ArrowBackIcon sx={{ fontSize: 40 }}/>
                </Button>
                :
                <Button
                    variant="outline"
                    disabled={true}
                    className={"row-start-2 row-span-2 col-start-1 col-span-1 w-fit h-fit self-center justify-self-center"}
                >
                    <ArrowBackIcon sx={{ fontSize: 40 }}/>
                </Button>
            }
            {index === cards.length - 1 ?
                <Button
                    onClick={addCard}
                    className={"row-start-2 row-span-2 col-start-4 col-span-1 w-fit h-fit self-center justify-self-center"}
                >
                    <AddIcon sx={{ fontSize: 40 }}/>
                </Button> :
                <Button
                    onClick={() => setIndex(index => index + 1)}
                    className={"row-start-2 row-span-2 col-start-4 col-span-1 w-fit h-fit self-center justify-self-center"}
                >
                    <ArrowForwardIcon sx={{ fontSize: 40 }}/>
                </Button>
            }
            {autoTranslate ?
                <Button
                    className={"row-start-4 row-span-1 col-start-1 col-span-1 w-fit h-fit self-center justify-self-center"}
                    onClick={() => setAutoTranslate(false)}
                >
                    Auto-translate enabled
                </Button> :
                <Button
                    variant="outline"
                    className={"row-start-4 row-span-1 col-start-1 col-span-1 w-fit h-fit self-center justify-self-center"}
                    onClick={() => setAutoTranslate(true)}
                >
                    Auto-translate disabled
                </Button>
            }

            {stackName.length !== 0 && cards.every(card => card.front.length !== 0 && card.back.length !== 0) ?
                <Button
                    onClick={saveStack}
                    className={"row-start-4 row-span-1 col-start-4 col-span-4 w-fit h-fit self-center justify-self-center"}
                >
                    Save flashcard Set
                </Button>
                :
                <Button
                    disabled={true}
                    variant="outline"
                    onClick={saveStack}
                    className={"row-start-4 row-span-1 col-start-4 col-span-4 w-fit h-fit self-center justify-self-center"}
                >
                    Save flashcard Set
                </Button>
            }


        </div>
    );
}
