'use client'

import { useState } from "react";
import {Flashcard} from "@/types/flashcard";
import NewFlashcard from "@/app/create/NewFlashcard";
import {TextField} from "@mui/material";
import {createClient} from "@/utils/supabase/client"
import {useRouter} from "next/navigation";
import "@/app/globals.css"

export default function CreateForm() {
    const [cards, setCards] = useState<Flashcard[]>([{id: 0, front: "", back: ""}]);
    const [nextID, setNextID] = useState(1);
    const [index, setIndex] = useState(0)
    const [stackName, setStackName] = useState("")
    const supabase = createClient()
    const router = useRouter()


    const addCard = () => {
        setCards(prev => [
            ...prev,
            { id: nextID, front: "", back: "" }
        ]);
        setNextID(nextID => nextID + 1)
        setIndex(index => index + 1)
    };

    const updateCard = (id: number, changes: Partial<Flashcard>) => {
        setCards(prev =>
            prev.map(card =>
                card.id == id ? { ...card, ...changes } : card
            )
        );
    };

    const deleteCard = (id: number) => {
        setCards(prev => prev.filter(card => card.id !== id));
    };

    const saveStack = async () => {
        const {
            data: {user}
        } = await supabase.auth.getUser()

        //save the flashcard stack object first
        const {data, error} = await supabase
            .from('flashcard_sets')
            .insert([
                {
                    user_id: user!.id,
                    //stack_id automatically generated by supabase
                    stack_name: stackName
                }
            ])
            .select('stack_id')

        //save each flashcard in the stack
        for (const card of cards) {
            await supabase
                .from('flashcards')
                .insert([
                    {
                        stack_id: data![0].stack_id,
                        front: card.front,
                        back: card.back
                    }
                ])
        }

        //redirect user to home page
        router.push("/")

    }

    return (
        <div className="grid grid-cols-4 grid-rows-4 w-screen h-screen">
            <TextField
                value={stackName}
                onChange={(e) => setStackName(e.target.value)}
                placeholder="Stack name"
                className={"col-span-2 col-start-2 row-span-1 row-start-1"}
                fullWidth={true}
            />
            <div
                className={"col-span-2 col-start-2 row-span-2 row-start-2"}>
                <NewFlashcard
                    key={cards[index].id}
                    card={cards[index]}
                    onUpdate={updateCard}
                    onDelete={deleteCard}
                />
                <button>Front</button>
            </div>
            {index !== 0 &&
                <button
                    onClick={() => setIndex(index => index - 1)}
                    className={"row-start-2 row-span-2 col-start-1 col-span-1"}
                >
                    Previous
                </button>
            }
            {index === cards.length - 1 ?
                <button
                    onClick={addCard}
                    className={"row-start-2 row-span-2 col-start-4 col-span-1"}
                >
                    Add
                </button> :
                <button
                    onClick={() => setIndex(index => index + 1)}
                    className={"row-start-2 row-span-2 col-start-4 col-span-1"}
                >
                    Next
                </button>
            }
            <button
                className={"row-start-4 row-span-1 col-start-1 col-span-1"}
            >
                Auto-translate enabled
            </button>
            <button
                onClick={saveStack}
                className={"row-start-4 row-span-1 col-start-4 col-span-4"}
            >
                Save flashcard Set
            </button>
        </div>
    );
}
